### ISSUE TITLE
Erstellen des leeren Unity Projects

### ISSUE THREAD

**Issue by plumskl0** [plumskl0/Keelan_Neo#1]
Leeres Projekt erstellen und pushen

**Comment by freiSMS** [comment]
Ah... sehr cool danke! Wenn du da dran bist kannst du den Status auf "inProgress" ändern. Oben unter "Project" werden dir die Issues dann getrennt nach Status angezeigt

**Comment by plumskl0** [comment]
Erledigt in 668148075c3250f0841889fb395e95a359623c05
