### ISSUE TITLE
Karten Entwurf umsetzen

### ISSUE THREAD

**Issue by plumskl0** [plumskl0/Keelan_Neo#14]

**Comment by freiSMS** [comment]
![grafik](https://user-images.githubusercontent.com/20289566/27427776-79553896-5740-11e7-95d4-9e3ebba62886.png)
Zone 1: nicht schwer, Spieler kann Münzen sammeln
Zone 2: besteht aus 3 Routen mit (Hindernisse & Hilfsmittel)
Route 1:
Hindernisse: schwieriges Gelände
Hilfsmittel: ein Rohr
Route 2:
Hindernisse: sehr windig
Hilfsmittel: Ändern des Ballgewichts
Route 3:
Hindernisse: Raben
Hilfsmittel: Verstecke
Zone 3: schwer zu fahren, keine Hilfsmittel


Da wir dieses Bild ja recht ausführlich in der Präsentation hatten sollten wir uns einigermaßen daran halten denke ich. Hast du da schon angefangen @AlMahamid ?

**Comment by freiSMS** [comment]
- [x] Map1 fertig und in Spiel integriert
